# Generated by Django 5.2.5 on 2025-08-24 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricehistory',
            options={'ordering': ['timestamp']},
        ),
        migrations.AlterModelOptions(
            name='trade',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RenameField(
            model_name='trade',
            old_name='trade_type',
            new_name='side',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='api_secret',
        ),
        migrations.AlterField(
            model_name='profile',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=10000.0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='trade',
            name='amount',
            field=models.DecimalField(decimal_places=8, max_digits=24),
        ),
        migrations.AlterUniqueTogether(
            name='currency',
            unique_together={('base_currency', 'quote_currency')},
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=8, default=0, max_digits=24)),
                ('currency_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.currency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'currency_pair')},
            },
        ),
        migrations.DeleteModel(
            name='PerformanceReport',
        ),
    ]
