# Generated by Django 5.2.5 on 2025-08-26 18:59

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_pricehistory_options_alter_trade_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricehistory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='trade',
            options={},
        ),
        migrations.RenameField(
            model_name='currency',
            old_name='current_rate',
            new_name='current_price',
        ),
        migrations.AlterUniqueTogether(
            name='holding',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='trade',
            name='total_value',
        ),
        migrations.AddField(
            model_name='holding',
            name='amount',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.0'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='currency',
            name='quote_currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='currency_pair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.currency'),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='profile',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('10000.00'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trade',
            name='amount',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
        migrations.AlterField(
            model_name='trade',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.RemoveField(
            model_name='holding',
            name='quantity',
        ),
    ]
