# Generated by Django 5.2.5 on 2025-08-28 18:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_pricehistory_options_alter_trade_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='usd_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20),
        ),
    ]
